"use strict";
let vararray1 = [1, 2, 3];
let vararray2 = [1, 2, 3];
let vararray3 = [1, 2, 3];
console.log(typeof vararray1 + " = " + vararray1);
console.log(typeof vararray2 + " = " + vararray2);
console.log(typeof vararray3 + " = " + vararray3);
let vararray4 = ["hi", "there", "everybody"];
let vararray5 = ["hi", "there", "everybody"];
let vararray6 = ["hi", "there", "everybody"];
console.log(typeof vararray4 + " = " + vararray4);
console.log(typeof vararray5 + " = " + vararray5);
console.log(typeof vararray6 + " = " + vararray6);
